cc_binary (
  name = "benchmark",
  srcs = [
  "threshold.h",
  "threshold.cc",
  "benchmark.cc",
  ],
  deps = ["@opencv//:lib", "@google_benchmark//:lib"],
  )

cc_binary (
  name = "demo",
  srcs = [
  "threshold.h",
  "threshold.cc",
  "demo.cc",
  ],
  deps = ["@opencv//:lib", "@google_benchmark//:lib"],
  )
